package constants

const (
	ERROR_CODE     = "err_code"
	ERROR_SOURCE   = "err_src"
	ERROR_SUB_CODE = "err_sub"

	ERR_SRC_REQUEST               = "REQ"
	ERR_MISSING_INFO_DEVICE_ID    = "M_DI"
	ERR_MISSING_INFO_ACCESS_TOKEN = "M_AT"
	ERR_MISSING_INFO_NIS_TOKEN    = "M_NT"
	ERR_MISSING_INFO_USER_ID      = "M_UI"
	ERR_MISSING_PUID              = "M_PI"
	ERR_REQUEST_UNKNOWN_APP       = "I_AP"
	ERR_REQUEST_INVALID_PROVIDER  = "I_PR"
	ERR_PHONE_ALREADY_EXISTS      = "PH_EXS"

	ERR_SRC_JWT                = "JWT"
	ERR_MISSING_JWT_SECRET_KEY = "M_JSK"
	ERR_JWT_TOKEN_GENERATION   = "JWT_GF"
	ERR_JWT_PARSE              = "JWT_PF"
	ERR_INVALID_JWT            = "I_JWT"

	ERR_EXPIRED_TOKEN  = "T_EX"
	ERR_JWT_VALIDATION = "T_VAL"

	ERR_SRC_GOOGLE                  = "GGL"
	ERR_SRC_FACEBOOK                = "FB"
	ERR_EXT_API_REQUEST             = "RQ_F"
	ERR_EXT_API_RESPONSE_PARSE      = "RS_PF"
	ERR_EXT_API_RESPONSE_FAILURE    = "RS_F"
	ERR_EXT_API_RESPONSE_BODY_CLOSE = "RS_BC"

	ERR_SRC_FIREBASE         = "FRB"
	ERR_CLIENT_BUILD_FAILURE = "CL_F"
	ERR_MISSING_CONFIG       = "M_CF"
	ERR_MISSING_CLIENT       = "M_CL"
	ERR_AUTH_FAIL            = "AU_F"
	ERR_MISSING_RECORD       = "M_RC"

	ERR_SRC_DATA_SOURCE        = "PR_DS"
	ERR_MISSING_EMAIL_AND_PUID = "M_E_PI"

	ERR_SRC_MONGO               = "MG"
	ERR_MGO_READ_INTERNAL       = "DB_IN_R"
	ERR_MGO_WRITE_INTERNAL      = "DB_IN_W"
	ERR_MGO_BULK_WRITE_INTERNAL = "DB_IN_BW"
)
